package com.joany.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GREEN_RX_NEWS".
 */
public class GreenRxNews {

    private Long id;
    private String newsResponse;
    private String type;

    public GreenRxNews() {
    }

    public GreenRxNews(Long id) {
        this.id = id;
    }

    public GreenRxNews(Long id, String newsResponse, String type) {
        this.id = id;
        this.newsResponse = newsResponse;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNewsResponse() {
        return newsResponse;
    }

    public void setNewsResponse(String newsResponse) {
        this.newsResponse = newsResponse;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
